#!/usr/bin/env python3
"""Train a goal-conditioned full-body H1 pose policy from MuJoCo states.

This is a safe behavioural-cloning bootstrap for reinforcement learning: every
sample is generated by the real full H1 MuJoCo model with randomized joint
perturbations.  It learns neutral, left-kneel, right-kneel and salute goals.
"""
import json
from pathlib import Path
import mujoco
import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "assets/unitree_h1/scene_full.xml"
OUT = ROOT / "assets/fullbody_goal_policy.json"
torch.manual_seed(41); rng = np.random.default_rng(41)
names = ["torso_joint", "left_hip_yaw_joint", "left_hip_roll_joint", "left_hip_pitch_joint", "left_knee_joint", "left_ankle_joint",
         "right_hip_yaw_joint", "right_hip_roll_joint", "right_hip_pitch_joint", "right_knee_joint", "right_ankle_joint",
         "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint",
         "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint"]
scale = np.array([1.2,.43,.43,1.57,2.05,.87,.43,.43,1.57,2.05,.87,2.2,1.5,2.2,2.0,2.2,1.5,2.2,2.0], np.float32)
# Neutral, left knee-down, right knee-down, arm salute. Targets are deliberately
# within joint limits; MuJoCo randomization gives the network recovery states.
targets = np.array([
 [0,0,0,-.40,.80,-.40,0,0,-.40,.80,-.40,0,0,0,0,0,0,0,0],
 [0,0,.12,-.82,1.58,-.48,0,-.12,-.38,.85,-.36,.52,.14,0,.75,.20,-.08,0,.48],
 [0,0,-.12,-.38,.85,-.36,0,.12,-.82,1.58,-.48,.20,.08,0,.48,.52,-.14,0,.75],
 [.25,0,0,-.18,.45,-.22,0,0,-.18,.45,-.22,-1.25,.20,.10,1.55,.55,-.10,0,.60]], np.float32)

m = mujoco.MjModel.from_xml_path(str(MODEL)); d = mujoco.MjData(m)
jids = np.array([mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_JOINT, n) for n in names])
qadr = m.jnt_qposadr[jids]; dadr = m.jnt_dofadr[jids]
features=[]; labels=[]
for goal, target in enumerate(targets):
    for _ in range(1400):
        mujoco.mj_resetData(m,d)
        d.qpos[qadr] = target + rng.normal(0,.16,len(names))
        d.qvel[dadr] = rng.normal(0,.45,len(names))
        mujoco.mj_forward(m,d)
        features.append(np.r_[d.qpos[qadr]/scale, .08*d.qvel[dadr], np.eye(4,dtype=np.float32)[goal]])
        labels.append(np.clip(target/scale,-.98,.98))
x=torch.tensor(np.asarray(features),dtype=torch.float32); y=torch.tensor(np.asarray(labels),dtype=torch.float32)
net=torch.nn.Sequential(torch.nn.Linear(42,96),torch.nn.Tanh(),torch.nn.Linear(96,19),torch.nn.Tanh())
opt=torch.optim.Adam(net.parameters(),lr=.008)
for _ in range(900):
    loss=((net(x)-y)**2).mean(); opt.zero_grad(); loss.backward(); opt.step()
a,b=net[0],net[2]
OUT.write_text(json.dumps({"format":"cao_fullbody_goal_mlp_v1","joints":names,"goals":["neutral","kneel_left","kneel_right","salute"],"joint_scales":scale.tolist(),"layer1_weight":a.weight.detach().tolist(),"layer1_bias":a.bias.detach().tolist(),"layer2_weight":b.weight.detach().tolist(),"layer2_bias":b.bias.detach().tolist()},indent=2)+"\n")
print(f"wrote {OUT}; mse={loss.item():.7f}; samples={len(features)}")
