#define GLFW_INCLUDE_NONE
#include <vulkan/vulkan.h>
#include <GLFW/glfw3.h>
#include <iostream>
#include <vector>
#include <stdexcept>
#include <string>
#include <algorithm>
static void check(VkResult r,const char*s){if(r!=VK_SUCCESS)throw std::runtime_error(std::string(s)+" "+std::to_string(r));}
int main(){try{if(!glfwInit())return 1;glfwWindowHint(GLFW_CLIENT_API,GLFW_NO_API);GLFWwindow*w=glfwCreateWindow(1280,800,"CAO Jolt Vulkan",nullptr,nullptr);if(!w)throw std::runtime_error("window");
 uint32_t en=0;const char** ext=glfwGetRequiredInstanceExtensions(&en);VkApplicationInfo ai{VK_STRUCTURE_TYPE_APPLICATION_INFO,nullptr,"CAO Jolt Vulkan",1,"CAO",1,VK_API_VERSION_1_0};VkInstanceCreateInfo ci{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,nullptr,0,&ai,0,nullptr,en,ext};VkInstance instance;check(vkCreateInstance(&ci,nullptr,&instance),"instance");VkSurfaceKHR surface;check(glfwCreateWindowSurface(instance,w,nullptr,&surface),"surface");
 uint32_t ng=0;vkEnumeratePhysicalDevices(instance,&ng,nullptr);std::vector<VkPhysicalDevice> gs(ng);vkEnumeratePhysicalDevices(instance,&ng,gs.data());VkPhysicalDevice gpu=VK_NULL_HANDLE;uint32_t family=0;for(auto g:gs){uint32_t nq=0;vkGetPhysicalDeviceQueueFamilyProperties(g,&nq,nullptr);std::vector<VkQueueFamilyProperties> qp(nq);vkGetPhysicalDeviceQueueFamilyProperties(g,&nq,qp.data());for(uint32_t i=0;i<nq;i++){VkBool32 present=0;vkGetPhysicalDeviceSurfaceSupportKHR(g,i,surface,&present);if(present&&(qp[i].queueFlags&VK_QUEUE_GRAPHICS_BIT)){gpu=g;family=i;break;}}if(gpu)break;}if(!gpu)throw std::runtime_error("no Vulkan GPU");float priority=1;VkDeviceQueueCreateInfo qci{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,nullptr,0,family,1,&priority};const char* dex[]={VK_KHR_SWAPCHAIN_EXTENSION_NAME};VkDeviceCreateInfo dci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,nullptr,0,1,&qci,0,nullptr,1,dex,nullptr};VkDevice device;check(vkCreateDevice(gpu,&dci,nullptr,&device),"device");VkQueue queue;vkGetDeviceQueue(device,family,0,&queue);
 VkSurfaceCapabilitiesKHR cap;vkGetPhysicalDeviceSurfaceCapabilitiesKHR(gpu,surface,&cap);uint32_t nf=0;vkGetPhysicalDeviceSurfaceFormatsKHR(gpu,surface,&nf,nullptr);if(!nf)throw std::runtime_error("Vulkan surface has no formats");std::vector<VkSurfaceFormatKHR> fm(nf);vkGetPhysicalDeviceSurfaceFormatsKHR(gpu,surface,&nf,fm.data());VkSurfaceFormatKHR sf=fm[0];uint32_t ni=std::max(2u,cap.minImageCount);if(cap.maxImageCount)ni=std::min(ni,cap.maxImageCount);VkExtent2D extent=cap.currentExtent;if(extent.width==UINT32_MAX){int width=0,height=0;glfwGetFramebufferSize(w,&width,&height);extent.width=std::clamp(static_cast<uint32_t>(width),cap.minImageExtent.width,cap.maxImageExtent.width);extent.height=std::clamp(static_cast<uint32_t>(height),cap.minImageExtent.height,cap.maxImageExtent.height);}VkImageUsageFlags usage=VK_IMAGE_USAGE_TRANSFER_DST_BIT;if((cap.supportedUsageFlags&usage)==0)throw std::runtime_error("Vulkan swapchain does not support transfer clear");VkCompositeAlphaFlagBitsKHR alpha=VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;if(!(cap.supportedCompositeAlpha&alpha)){if(cap.supportedCompositeAlpha&VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR)alpha=VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR;else if(cap.supportedCompositeAlpha&VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR)alpha=VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR;else alpha=VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR;}VkSwapchainCreateInfoKHR sci{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR,nullptr,0,surface,ni,sf.format,sf.colorSpace,extent,1,usage,VK_SHARING_MODE_EXCLUSIVE,0,nullptr,cap.currentTransform,alpha,VK_PRESENT_MODE_FIFO_KHR,VK_TRUE,VK_NULL_HANDLE};VkSwapchainKHR swap;check(vkCreateSwapchainKHR(device,&sci,nullptr,&swap),"swapchain");uint32_t count=0;vkGetSwapchainImagesKHR(device,swap,&count,nullptr);std::vector<VkImage> imgs(count);vkGetSwapchainImagesKHR(device,swap,&count,imgs.data());
 VkCommandPool pool;VkCommandPoolCreateInfo pci{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,nullptr,VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT,family};check(vkCreateCommandPool(device,&pci,nullptr,&pool),"pool");std::vector<VkCommandBuffer> cb(count);VkCommandBufferAllocateInfo cai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,nullptr,pool,VK_COMMAND_BUFFER_LEVEL_PRIMARY,count};check(vkAllocateCommandBuffers(device,&cai,cb.data()),"buffers");VkSemaphore acquire,done;VkSemaphoreCreateInfo sem{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};vkCreateSemaphore(device,&sem,nullptr,&acquire);vkCreateSemaphore(device,&sem,nullptr,&done);VkFence fence;VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO,nullptr,VK_FENCE_CREATE_SIGNALED_BIT};vkCreateFence(device,&fi,nullptr,&fence);
 while(!glfwWindowShouldClose(w)){glfwPollEvents();vkWaitForFences(device,1,&fence,VK_TRUE,UINT64_MAX);vkResetFences(device,1,&fence);uint32_t ix;VkResult ar=vkAcquireNextImageKHR(device,swap,UINT64_MAX,acquire,VK_NULL_HANDLE,&ix);if(ar==VK_ERROR_OUT_OF_DATE_KHR)continue;check(ar,"acquire");VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};vkBeginCommandBuffer(cb[ix],&bi);VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,nullptr,0,VK_ACCESS_TRANSFER_WRITE_BIT,VK_IMAGE_LAYOUT_UNDEFINED,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,VK_QUEUE_FAMILY_IGNORED,VK_QUEUE_FAMILY_IGNORED,imgs[ix],{VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1}};vkCmdPipelineBarrier(cb[ix],VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&b);VkClearColorValue color{{0.03f,0.14f,0.22f,1}};VkImageSubresourceRange range{VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};vkCmdClearColorImage(cb[ix],imgs[ix],VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,&color,1,&range);b.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;b.dstAccessMask=0;b.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b.newLayout=VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;vkCmdPipelineBarrier(cb[ix],VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,0,0,nullptr,0,nullptr,1,&b);vkEndCommandBuffer(cb[ix]);VkPipelineStageFlags stage=VK_PIPELINE_STAGE_TRANSFER_BIT;VkSubmitInfo sub{VK_STRUCTURE_TYPE_SUBMIT_INFO,nullptr,1,&acquire,&stage,1,&cb[ix],1,&done};check(vkQueueSubmit(queue,1,&sub,fence),"submit");VkPresentInfoKHR pi{VK_STRUCTURE_TYPE_PRESENT_INFO_KHR,nullptr,1,&done,1,&swap,&ix,nullptr};vkQueuePresentKHR(queue,&pi);}
 vkDeviceWaitIdle(device);vkDestroyFence(device,fence,nullptr);vkDestroySemaphore(device,done,nullptr);vkDestroySemaphore(device,acquire,nullptr);vkDestroyCommandPool(device,pool,nullptr);vkDestroySwapchainKHR(device,swap,nullptr);vkDestroyDevice(device,nullptr);vkDestroySurfaceKHR(instance,surface,nullptr);vkDestroyInstance(instance,nullptr);glfwDestroyWindow(w);glfwTerminate();return 0;}catch(const std::exception&e){std::cerr<<"Fatal: "<<e.what()<<"\n";return 4;}}
